# Generated by Django 5.2.7 on 2025-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_admin_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='สิทธิการอนุมัติ'),
        ),
    ]
