# Generated by Django 5.2.7 on 2025-12-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
