# Generated by Django 5.2.7 on 2025-10-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='รหัสนักเรียน')),
                ('first_name', models.CharField(max_length=50, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=50, verbose_name='นามสกุล')),
                ('grade_level', models.CharField(max_length=20, verbose_name='ระดับชั้น')),
                ('classroom', models.CharField(max_length=20, verbose_name='ห้องเรียน')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
                ('guardian_name', models.CharField(max_length=100, verbose_name='ชื่อผู้ปกครอง')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลผู้ปกครอง')),
            ],
        ),
    ]
