# Generated by Django 5.2.7 on 2025-10-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.CharField(default='', max_length=20, verbose_name='ห้องเรียน'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(max_length=20, verbose_name='ระดับชั้น'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อรายวิชา'),
        ),
    ]
