# Generated by Django 5.2.7 on 2025-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_subject_classroom_alter_subject_grade_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, verbose_name='รหัสวิชา')),
                ('subject_name', models.CharField(max_length=100, verbose_name='ชื่อวิชา')),
                ('test_name', models.CharField(max_length=100, verbose_name='ชื่อแบบทดสอบ')),
                ('answer_key', models.JSONField(verbose_name='เฉลย')),
                ('full_score', models.PositiveIntegerField(default=100, verbose_name='คะแนนเต็ม')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='ชื่อครูผู้สอน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('exam_date', models.DateField(verbose_name='วันที่จัดสอบ')),
            ],
            options={
                'verbose_name': 'ข้อมูลแบบทดสอบ',
                'verbose_name_plural': 'ข้อมูลแบบทดสอบทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
