# Generated by Django 5.2.7 on 2025-11-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_is_approved'),
        ('quiz', '0005_remove_subject_teacher_subject_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_subjects', to='accounts.teacherprofile'),
        ),
    ]
